---
# Namespace for Dev Environment
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-dev
  labels:
    environment: dev
    app: podinfo

---

# SecurityContextConstraints for podinfo
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: podinfo-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:podinfo-dev:podinfo
- system:serviceaccount:podinfo-prod:podinfo
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret

---

# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podinfo
  namespace: podinfo-dev

---

# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-config
  namespace: podinfo-dev
data:
  PODINFO_UI_COLOR: "#34577c"
  PODINFO_UI_MESSAGE: "Deployed on OpenShift via Harness GitOps"
  PODINFO_BACKEND_URL: ""
  PODINFO_CACHE_SERVER: ""

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: podinfo-dev
  labels:
    app: podinfo
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: podinfo
        environment: dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9898"
    spec:
      serviceAccountName: podinfo
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      containers:
      - name: podinfo
        image: image-registry.openshift-image-registry.svc:5000/podinfo-dev/podinfo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        command:
          - ./podinfo
          - --port=9898
          - --port-metrics=9797
          - --grpc-port=9999
          - --grpc-service-name=podinfo
          - --level=info
          - --random-delay=false
          - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          valueFrom:
            configMapKeyRef:
              name: podinfo-config
              key: PODINFO_UI_COLOR
        - name: PODINFO_UI_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: podinfo-config
              key: PODINFO_UI_MESSAGE
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /data
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo-dev
  labels:
    app: podinfo
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
  - name: http
    port: 9898
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9999
    targetPort: grpc
    protocol: TCP

---

# OpenShift Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: podinfo
  namespace: podinfo-dev
  labels:
    app: podinfo
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: podinfo
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

---

# HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
  namespace: podinfo-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
