---
# Namespace for Prod Environment
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-prod
  labels:
    environment: prod
    app: podinfo

---

# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podinfo
  namespace: podinfo-prod

---

# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-config
  namespace: podinfo-prod
data:
  PODINFO_UI_COLOR: "#1e3a8a"
  PODINFO_UI_MESSAGE: "Production - Deployed on OpenShift via Harness GitOps"
  PODINFO_BACKEND_URL: ""
  PODINFO_CACHE_SERVER: ""

---

# Primary Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: podinfo-prod
  labels:
    app: podinfo
    environment: prod
    version: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podinfo
      version: stable
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: podinfo
        environment: prod
        version: stable
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9898"
    spec:
      serviceAccountName: podinfo
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - podinfo
              topologyKey: kubernetes.io/hostname
      containers:
      - name: podinfo
        image: image-registry.openshift-image-registry.svc:5000/podinfo-prod/podinfo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        command:
          - ./podinfo
          - --port=9898
          - --port-metrics=9797
          - --grpc-port=9999
          - --grpc-service-name=podinfo
          - --level=info
          - --random-delay=false
          - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          valueFrom:
            configMapKeyRef:
              name: podinfo-config
              key: PODINFO_UI_COLOR
        - name: PODINFO_UI_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: podinfo-config
              key: PODINFO_UI_MESSAGE
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /data
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}

---

# Primary Service
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo-prod
  labels:
    app: podinfo
spec:
  type: ClusterIP
  selector:
    app: podinfo
    version: stable
  ports:
  - name: http
    port: 9898
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9999
    targetPort: grpc
    protocol: TCP

---

# Staging Service (for Blue-Green deployments)
apiVersion: v1
kind: Service
metadata:
  name: podinfo-stage
  namespace: podinfo-prod
  labels:
    app: podinfo
spec:
  type: ClusterIP
  selector:
    app: podinfo
    version: stage
  ports:
  - name: http
    port: 9898
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9999
    targetPort: grpc
    protocol: TCP

---

# OpenShift Route (Production)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: podinfo
  namespace: podinfo-prod
  labels:
    app: podinfo
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: podinfo
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

---

# OpenShift Route (Staging - for testing before swap)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: podinfo-stage
  namespace: podinfo-prod
  labels:
    app: podinfo
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: podinfo-stage
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

---

# HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
  namespace: podinfo-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70

---

# PodDisruptionBudget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: podinfo
  namespace: podinfo-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: podinfo
