kind: pipeline
name: oc-refresh-poc

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone http://10.32.12.9:3030/git/gitness_demo/harness-gitops-workshop.git .
      - git checkout ${DRONE_COMMIT}

  - name: deploy
    image: openshift/origin-cli:latest
    commands:
      - echo "nameserver 10.36.65.10" > /etc/resolv.conf
      - echo "nameserver 10.32.65.11" >> /etc/resolv.conf
      - cat /etc/resolv.conf
      - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify=true
      - oc apply -f cli-manifests/ -n gitness-demo
      - oc get pods -n gitness-demo
    environment:
      OPENSHIFT_SERVER:
        from_secret: openshift_server
      OPENSHIFT_TOKEN:
        from_secret: openshift_token