pipeline:
  name: demo-ci-cd-pipeline
  identifier: democicdpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_connector
        repoName: harness-gitops-workshop
        build: <+input>
  stages:
    - stage:
        name: Build and Push
        identifier: build_and_push
        description: Build with Maven and push to DockerHub
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Go Tests
                  identifier: run_tests
                  spec:
                    connectorRef: docker_hub_connector
                    image: golang:1.20-alpine
                    shell: Sh
                    command: |
                      cd apps/podinfo
                      echo "Running Go tests..."
                      go test -v ./pkg/... || echo "Tests completed"
              
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push to DockerHub
                  identifier: build_push_docker
                  spec:
                    connectorRef: docker_hub_connector
                    repo: <+pipeline.variables.dockerRepo>
                    tags:
                      - <+pipeline.sequenceId>
                      - latest
                      - <+codebase.commitSha>
                    dockerfile: apps/podinfo/Dockerfile
                    context: apps/podinfo
                    labels:
                      app: podinfo
                      build: <+pipeline.sequenceId>
                    optimize: true
        variables:
          - name: BUILD_TIME
            type: String
            value: <+pipeline.executionStartTime>
    
    - stage:
        name: Deploy to OpenShift Dev
        identifier: deploy_dev
        description: Deploy to OpenShift with health checks
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: podinfo_service
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: podinfo_docker
                      sources:
                        - identifier: podinfo_docker
                          type: DockerRegistry
                          spec:
                            connectorRef: docker_hub_connector
                            imagePath: kannam/podinfo
                            tag: latest
          environment:
            environmentRef: dev_environment
            deployToAll: false
            infrastructureDefinitions:
              - identifier: openshift_dev_infra
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: Rolling Deployment
                  identifier: rolling_deploy
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
              
              - step:
                  type: ShellScript
                  name: Health Check
                  identifier: health_check
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          #!/bin/bash
                          set -e
                          
                          echo "Running health checks..."
                          
                          # Wait for pods to be ready
                          oc wait --for=condition=ready pod -l app=podinfo -n podinfo-dev --timeout=300s
                          
                          # Get pod count
                          POD_COUNT=$(oc get pods -n podinfo-dev -l app=podinfo --field-selector=status.phase=Running --no-headers | wc -l)
                          echo "Running pods: $POD_COUNT"
                          
                          if [ "$POD_COUNT" -lt 1 ]; then
                            echo "ERROR: No running pods found"
                            exit 1
                          fi
                          
                          echo "Health check passed!"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 5m
              
              - step:
                  type: ShellScript
                  name: Verify Deployment
                  identifier: verify_deployment
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          #!/bin/bash
                          echo "Verifying deployment..."
                          
                          # Check deployment status
                          oc rollout status deployment/podinfo -n podinfo-dev --timeout=5m
                          
                          # Get deployment info
                          oc get deployment podinfo -n podinfo-dev
                          
                          # Get route info
                          ROUTE=$(oc get route podinfo -n podinfo-dev -o jsonpath='{.spec.host}' 2>/dev/null || echo "No route found")
                          echo "Application route: $ROUTE"
                          
                          echo "Deployment verified successfully!"
                  timeout: 5m
            
            rollbackSteps:
              - step:
                  type: K8sRollingRollback
                  name: Rollback on Failure
                  identifier: rollback
                  spec:
                    pruningEnabled: false
                  timeout: 10m
              
              - step:
                  type: ShellScript
                  name: Notify Rollback
                  identifier: notify_rollback
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "=== AUTOMATIC ROLLBACK TRIGGERED ==="
                          echo "Deployment failed validation"
                          echo "Application rolled back to previous version"
        
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        
        when:
          pipelineStatus: Success
  
  variables:
    - name: dockerRepo
      type: String
      description: DockerHub repository
      required: true
      value: kannam/podinfo
  
  notificationRules:
    - name: Pipeline Success
      identifier: success_notification
      pipelineEvents:
        - type: PipelineSuccess
      notificationMethod:
        type: Email
        spec:
          userGroups:
            - account._account_all_users
          recipients:
            - <+pipeline.triggeredBy.email>
    
    - name: Pipeline Failed
      identifier: failure_notification
      pipelineEvents:
        - type: PipelineFailed
      notificationMethod:
        type: Email
        spec:
          userGroups:
            - account._account_all_users
          recipients:
            - <+pipeline.triggeredBy.email>
